### ISSUE TITLE
Team3 [4pt] Display dragons - Lists render

### ISSUE THREAD

**Issue by PRATAP-KUMAR** [PRATAP-KUMAR/react-group-project#14]
- Use `useSelector()` Redux Hook to select the state slices and render lists of dragons in corresponding routes. i.e.:
```javascript
// get rockets data from the store
const rockets = useSelector(state => state.rockets);
```

- You can style the whole application "by hand" or you could use [React Bootstrap](https://react-bootstrap.github.io/), a UI library that could speed up the process. This is a popular library and working with its components would be good practice.

- Render a list of dragons (as per design). For the image of a dragon use the first image in the array of `flickr_images`.

**Comment by uisendy** [comment]
### MileStone completed

Exercise Snapshot:
![image](https://user-images.githubusercontent.com/95294594/192719804-fae2dfab-0571-4521-b86a-6d6771c1ecbb.png)

The following was performed in this milestone , 

Use useSelector(), Redux Hook, to select the state slices and render lists of dragons in corresponding routes. ✅ 
Render a list of dragons (as per design) ✅ 
styling ✅
