### ISSUE TITLE
Team3 [1pt] Create basic structure for Dragons - Setup

### ISSUE THREAD

**Issue by PRATAP-KUMAR** [PRATAP-KUMAR/react-group-project#19]
- Create a route and a view component. Use `<NavLink />` for the page navigation links and style active class to indicate which section/page the user is currently on (underline active navigation link).
- Create a directory for all Redux state slice files.

**Comment by uisendy** [comment]
Create basic structure for Dragons -SetUp

The page was created , link added and routing enabled,styling to indicate the action section was also completed. 

Milestone completed ✅
