### ISSUE TITLE
Team3 [1pt] Switch badges for Dragons - Conditional components

### ISSUE THREAD

**Issue by PRATAP-KUMAR** [PRATAP-KUMAR/react-group-project#4]
Dragons that have already been reserved should show a "Reserved" badge and "Cancel reservation" button instead of the default "Reserve dragon" (as per design).

Use the React conditional rendering syntax:
```javascript
{rocket.reserved && ( 
    // render Cancel Rocket button
)}
```

**Comment by uisendy** [comment]
Milestone completed. 

![image](https://user-images.githubusercontent.com/95294594/192786703-548b9c2f-6bd2-41ef-8946-f7ee80103db8.png)


Booked Dragons are indicated with **reserved** tag and a cancellation button instead of the Reserve Dragon button.
