### ISSUE TITLE
React group project

### ISSUE THREAD

**Issue by uisendy** [PRATAP-KUMAR/react-group-project#43]
### React group project
We are a team of Three:
        @PRATAP-KUMAR
        @AbelG101
        @uisendy
[Here's the link](https://github.com/PRATAP-KUMAR/react-group-project/projects/3) to our project setup (kanban board).

**Comment by PRATAP-KUMAR** [comment]
Hi @uisendy yes, thanks for the edit. while you joined late in the afternoon we have already completed this project. That's why we could not add you. Now you did a good job.
